In [1]:
import pandas as pd
import numpy as np
import os

In [5]:
import pandas as pd

path = "retraite_placements_2012-2024.xlsx"

df = pd.read_csv(
    path,
    encoding="utf-8-sig"
)

display(df.head())
print(df.shape)
print(df.columns.tolist())

                    regime  annee  actifs_cotisants
0  Régimes complémentaires   2012      27254.896738
1          Régimes de base   2012     200606.311786
2  Régimes complémentaires   2013      30813.945064
3          Régimes de base   2013     211026.077169
4  Régimes complémentaires   2014      34431.085992

(26, 3)
['regime', 'annee', 'actifs_cotisants']

In [6]:
df = df.rename(columns={
    "actifs_cotisants": "placements"
})

df["annee"] = df["annee"].astype(int)
df["placements"] = pd.to_numeric(
    df["placements"],
    errors="coerce"
)

df = df.sort_values(
    ["annee", "regime"]
).reset_index(drop=True)

display(df)

                     regime  annee     placements
0   Régimes complémentaires   2012   27254.896738
1           Régimes de base   2012  200606.311786
2   Régimes complémentaires   2013   30813.945064
3           Régimes de base   2013  211026.077169
4   Régimes complémentaires   2014   34431.085992
5           Régimes de base   2014  223948.178256
6   Régimes complémentaires   2015   39161.437683
7           Régimes de base   2015  230989.644441
8   Régimes complémentaires   2016   44088.514141
9           Régimes de base   2016  238412.145627
10  Régimes complémentaires   2017   49273.021202
11          Régimes de base   2017  246266.001536
12  Régimes complémentaires   2018   55059.321098
13          Régimes de base   2018  254512.494609
14  Régimes complémentaires   2019   61268.928109
15          Régimes de base   2019  259324.833387
16  Régimes complémentaires   2020   66048.871247
17          Régimes de base   2020  262371.393561
18  Régimes complémentaires   2021   71866.144549
19          Régimes de base   2021  260160.670155
20  Régimes complémentaires   2022   75955.908581
21          Régimes de base   2022  251422.495078
22  Régimes complémentaires   2023   83324.173465
23          Régimes de base   2023  252039.281504
24  Régimes complémentaires   2024   92196.279962
25          Régimes de base   2024  255552.488271

In [7]:
print("Dimensions :", df.shape)
print("\nValeurs manquantes :")
print(df.isna().sum())

print("\nTypes :")
print(df.dtypes)

Dimensions : (26, 3)

Valeurs manquantes :
regime        0
annee         0
placements    0
dtype: int64

Types :
regime            str
annee           int64
placements    float64
dtype: object

In [8]:
df.to_csv(
    "placements_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Placements nettoyé et enregistré")

✅ Placements nettoyé et enregistré